* Find directed cycles that start and end at the same node
* Add time window filtering to focus on rapid circular transactions (e.g. within 3 days)
* Detect cyclic regions by finding groups of accounts that can reach each other â€” strongly connected components
* Frequency-based cycle scoring - rank cycles by how frequently they occur
* Find large-value circular flows if you only care about loops moving a lot of money

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'entity_name'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/diederickdebuck/.ansible/tmp/ansible-tmp-1761655200.297614-37065-79080054318824/AnsiballZ_label.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/Users/diederickdebuck/.ansible/tmp/ansible-tmp-1761655200.297614-37065-79080054318824/AnsiballZ_label.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/diederickdebuck/.ansible/tmp/ansible-tmp-1761655200.297614-37065-79080054318824/AnsiballZ_label.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.platform42.neo4j.plugins.modules.label', init_globals=dict(_module_fqn='ansible_collections.platform42.neo4j.plugins.modules.label', _modlib_path=modlib_path),\n  
File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  
File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  
File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/z5/1pb7vv7j5rl70ghkj4_flf9h0000gn/T/ansible_platform42.neo4j.label_payload_tod9odxd/ansible_platform42.neo4j.label_payload.zip/ansible_collections/platform42/neo4j/plugins/modules/label.py\", line 171, in <module>\n
  File \"/var/folders/z5/1pb7vv7j5rl70ghkj4_flf9h0000gn/T/ansible_platform42.neo4j.label_payload_tod9odxd/ansible_platform42.neo4j.label_payload.zip/ansible_collections/platform42/neo4j/plugins/modules/label.py\", line 134, in main\n  
  File \"/var/folders/z5/1pb7vv7j5rl70ghkj4_flf9h0000gn/T/ansible_platform42.neo4j.label_payload_tod9odxd/ansible_platform42.neo4j.label_payload.zip/ansible_collections/platform42/neo4j/plugins/modules/label.py\", line 72, in label\n  
  File \"/var/folders/z5/1pb7vv7j5rl70ghkj4_flf9h0000gn/T/ansible_platform42.neo4j.label_payload_tod9odxd/ansible_platform42.neo4j.label_payload.zip/ansible_collections/platform42/neo4j/plugins/module_utils/cypher.py\", line 174, in label_add\n
  File \"/var/folders/z5/1pb7vv7j5rl70ghkj4_flf9h0000gn/T/ansible_platform42.neo4j.label_payload_tod9odxd/ansible_platform42.neo4j.label_payload.zip/ansible_collections/platform42/neo4j/plugins/module_utils/cypher_query.py\", line 289, in cypher_label_add\nKeyError: 'entity_name'\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}
